#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: Register and subscribe to multiple pools.
      redhat_subscription:
        state: present
        username: "{{ _rhn_username }}"
        password: "{{ _rhn_password }}"
        pool_ids:
        - "{{ rhn_pool_id }}"

#    - name: Ensure dnf installed
#      yum:
#        name: dnf
#        state: latest
