#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: false
  become: true
  serial: 1
  tasks:
    - name: Load a variable file
      include_vars: "{{ lookup('first_found', possible_files) }}"
      vars:
        possible_files:
          - default.yaml

    - name: Register and subscribe to multiple pools.
      redhat_subscription:
        state: present
        username: "{{ _rhn_username }}"
        password: "{{ _rhn_password }}"
        pool_ids:
        - "{{ _rhn_pool_id }}"

#    - name: Ensure dnf installed
#      yum:
#        name: dnf
#        state: latest
